### PR TITLE
Casing thought

### PR DESCRIPTION
**Pull request by jonsherrard**
I think @garethfoote @ecoad and myself discussed whether we should maintain WordPress snake-case when we're writing in the WordPress ecosystem.

I had a look at other plugins we've written and we use snake_case in general.

This is just an example PR, and a point of discussion - it doesn't necessarily need to be merged.

This didn't take me very long, because I'm leet and use vim - if anyone was wondering.

@shortlist-digital/owners

### CODE REVIEW

**Comment by KimberleyCook** [comment]
@jonsherrard Leet?

**Comment by jonsherrard** [comment]
https://en.wikipedia.org/wiki/Leet (It's lame)

**Comment by iamdeaneyelid** [comment]
This makes sense.

**Comment by ecoad** [comment]
Ah great. I had this very thought this morning actually! Camel case is a hard habit to shake. Yes 🐍

**Pull request merged**
