### PR TITLE
getComponentStyles added to postcontroller

### PR DESCRIPTION
**Pull request by KimberleyCook**
start of 'general' styles added to PostController - I do think this controller file should get split up soon as this function could get very long

@ecoad @iamdeaneyelid @jonsherrard

### CODE REVIEW

**Comment by ecoad** [comment]
Yes good thought, split the Controller!

**Comment by KimberleyCook** [comment]
@ecoad Yeah, will do this first thing tomorrow

**Comment by ecoad** [comment]
@KimberleyCook What do you want to do about this PR? Leave it or merge it?

**Comment by KimberleyCook** [comment]
@ecoad Probably needs deleting as it is outdated now, plus I merged in the work yesterday to the develop branch

**Pull request closed without merging**
